---
output: pdf_document
header-includes:
- \usepackage{fullpage} 
- \usepackage[spanish]{babel}
- \setlength{\headsep}{7mm} 
- \usepackage[linktoc=page]{hyperref}
- \usepackage{fancyhdr}
- \usepackage{floatrow}
- \floatsetup[figure]{capposition=top}
- \floatsetup[table]{style=plaintop}
- \usepackage{float}
- \floatplacement{figure}{H}
- \newcommand{\beginsupplement}{
  \setcounter{table}{52}  
  \renewcommand{\thetable}{\arabic{table}} 
  \setcounter{figure}{125} 
  \renewcommand{\thefigure}{\arabic{figure}}}
- \setlength{\headheight}{13.6pt}
- \setlength{\topmargin}{-10mm}
- \rhead{Minería de Datos}
- \lhead{Entrega D3}
---

\pagenumbering{arabic}
\pagestyle{fancy}

```{=tex}
\cfoot{\thepage}
\setcounter{page}{149}
```
\beginsupplement


# Anexo

## Profiling Fuzzy


```{r, include=FALSE}
#Lectura de los datos
load("Dades preprocessades.Rdata")
mydata <- df_preprocessed
mydata[,c("AMT_INCOME_TOTAL","AMT_CREDIT","AMT_ANNUITY","AMT_GOODS_PRICE",
          "DAYS_BIRTH","TARGET","log_AMT_GOODS_PRICE","log_AMT_ANNUITY",
          "DIFF_CREDIT_GOODS")] <- NULL
dades <- mydata

# 
load("clust_fuzzy.Rdata")
cluster <- clusters
library(ggplot2)
```

```{r,include=FALSE}
indices_categoricas <- sapply(dades, is.factor)
p_values <- numeric(length(dades))

# Realiza pruebas de chi-cuadrado para las variables categóricas
for (i in which(indices_categoricas)) {
  variable_categorica <- dades[, i]
  cross_table <- table(variable_categorica, cluster)
  chi_square_result <- chisq.test(cross_table)
  p_values[i] <- chi_square_result$p.value
}


# Muestra los resultados
p_values_categoricas <- data.frame(
  Variable = names(dades)[indices_categoricas],
  P_Value = p_values[indices_categoricas]
)
```

```{r,include=FALSE}
library(car)
# Identifica las variables categóricas (factores)
variables_categoricas <- sapply(dades, is.factor)

# Filtra las variables numéricas
variables_numericas <- dades[!variables_categoricas]
# Inicializa un objeto para almacenar los p valores de la ANOVA
p_values_numericas <- list()

# Realiza un ANOVA para cada variable numérica en función de cluster6 y cluster3
for (i in 1:ncol(variables_numericas)) {
  variable_name <- names(variables_numericas)[i]
  
  formula_cluster <- as.formula(paste(variable_name, " ~ cluster"))
  anova_result_cluster <- Anova(lm(formula_cluster, data = variables_numericas))
  
  # Almacena los p-valores de la ANOVA en p_values_anova
  p_values_numericas[[variable_name]] <- c(Cluster = anova_result_cluster[["Pr(>F)"]][1])
}
```


```{r,include=FALSE}
library(ggplot2)
colores <- scales::brewer_pal(palette = "Set1")(length(unique(cluster)))
```

```{r, warning=FALSE,echo=FALSE, fig.cap = "Medias de la Edad en años del coche del cliente por clúster respecto la media global", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, y = dades$OWN_CAR_AGE)) + 
  geom_bar(stat = "summary", fun = "mean", fill= colores) +
  geom_hline(yintercept = mean(dades$OWN_CAR_AGE)) +
  labs(title = "Medias de la Edad en años del coche del cliente por clúster respecto la media global" , y = "Media", x = "Clúster") 
```

```{r, warning=FALSE,echo=FALSE, fig.cap = "Medias del Número de familiares del cliente por clúster respecto la media global" , fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, y = dades$CNT_FAM_MEMBERS)) +
  geom_bar(stat = "summary", fun = "mean", fill= colores) +
  geom_hline(yintercept = mean(dades$CNT_FAM_MEMBERS)) +
  labs(title = "Medias del Número de familiares del cliente por clúster respecto la media global" , y = "Media", x = "Clúster")
```

```{r, warning=FALSE,echo=FALSE, fig.cap = "Medias del logaritmo de los Ingresos totales del cliente por clúster respecto la media global", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, y = dades$log_AMT_INCOME_TOTAL)) +
  geom_bar(stat = "summary", fun = "mean", fill= colores) +
  geom_hline(yintercept = mean(dades$log_AMT_INCOME_TOTAL)) +
  labs(title = "Medias del logaritmo de los Ingresos totales del cliente por clúster respecto la media global" , y = "Media", x = "Clúster") 
```

```{r, warning=FALSE,echo=FALSE, fig.cap = "Medias del Importe de crédito del préstamo por clúster respecto la media global", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, y = dades$log_AMT_CREDIT)) +
  geom_bar(stat = "summary", fun = "mean", fill= colores) +
  geom_hline(yintercept = mean(dades$log_AMT_CREDIT)) +
  labs(title = "Medias del Importe de crédito del préstamo por clúster respecto la media global" , y = "Media", x = "Clúster")

```

```{r, warning=FALSE,echo=FALSE, fig.cap = "Medias de la Edad por clúster respecto la media global", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, y = dades$AGE_YEARS)) +
  geom_bar(stat = "summary", fun = "mean", fill= colores) +
  geom_hline(yintercept = mean(dades$AGE_YEARS)) +
  labs(title = "Medias de la Edad por clúster respecto la media global" , y = "Media", x = "Clúster")

```

```{r, warning=FALSE,echo=FALSE, fig.cap = "Gráfico de la distribución del Género respecto el Clúster", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, fill = dades$CODE_GENDER)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución del Género respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))
```

```{r, warning=FALSE,echo=FALSE, fig.cap = "Gráfico de la distribución del Tipo de ingresos respecto el Clúster", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, fill = dades$NAME_INCOME_TYPE)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución del Tipo de ingresos respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))
```

```{r, warning=FALSE,echo=FALSE, fig.cap = "Gráfico de la distribución del Nivel de estudios del cliente respecto el Clúster", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, fill = dades$NAME_EDUCATION_TYPE)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución del Nivel de estudios del cliente respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))
```

```{r, warning=FALSE,echo=FALSE, fig.cap =  "Gráfico de la distribución del Estado civil respecto el Clúster", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, fill = dades$NAME_FAMILY_STATUS)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución del Estado civil respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))
```

```{r, warning=FALSE,echo=FALSE, fig.cap = "Gráfico de la distribución de la Actividad laboral respecto el Clúster", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, fill = dades$OCCUPATION_TYPE)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución de la Actividad laboral respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))
```

```{r, warning=FALSE,echo=FALSE, fig.cap = "Gráfico de la distribución del Tipo de organización donde trabaja el cliente respecto el Clúster", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, fill = dades$ORGANIZATION_TYPE)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución del Tipo de organización donde trabaja el cliente respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))
```

```{r, warning=FALSE,echo=FALSE, fig.cap =  "Gráfico de la distribución de la Calificación de la región donde vive el cliente", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, fill = dades$REGION_RATING_CLIENT)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución de la Calificación de la región donde vive el cliente respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))
```


## Profiling k-means

```{r, include=FALSE}
#Lectura de los datos
load("Dades preprocessades.Rdata")
mydata <- df_preprocessed
mydata[,c("AMT_INCOME_TOTAL","AMT_CREDIT","AMT_ANNUITY","AMT_GOODS_PRICE",
          "DAYS_BIRTH","TARGET","log_AMT_GOODS_PRICE","log_AMT_ANNUITY",
          "DIFF_CREDIT_GOODS")] <- NULL
dades <- mydata

# 
load("todoslosdatosclustjer.Rdata")
cluster <- resultado$cluster
```

```{r, include=FALSE}
indices_categoricas <- sapply(dades, is.factor)
p_values <- numeric(length(dades))

# Realiza pruebas de chi-cuadrado para las variables categóricas
for (i in which(indices_categoricas)) {
  variable_categorica <- dades[, i]
  cross_table <- table(variable_categorica, cluster)
  chi_square_result <- chisq.test(cross_table)
  p_values[i] <- chi_square_result$p.value
}


# Muestra los resultados
p_values_categoricas <- data.frame(
  Variable = names(dades)[indices_categoricas],
  P_Value = p_values[indices_categoricas]
)
print(p_values_categoricas)
```

```{r, include=FALSE}
library(car)
# Identifica las variables categóricas (factores)
variables_categoricas <- sapply(dades, is.factor)

# Filtra las variables numéricas
variables_numericas <- dades[!variables_categoricas]
# Inicializa un objeto para almacenar los p valores de la ANOVA
p_values_numericas <- list()

# Realiza un ANOVA para cada variable numérica en función de cluster6 y cluster3
for (i in 1:ncol(variables_numericas)) {
  variable_name <- names(variables_numericas)[i]
  
  formula_cluster <- as.formula(paste(variable_name, " ~ cluster"))
  anova_result_cluster <- Anova(lm(formula_cluster, data = variables_numericas))
  
  # Almacena los p-valores de la ANOVA en p_values_anova
  p_values_numericas[[variable_name]] <- c(Cluster = anova_result_cluster[["Pr(>F)"]][1])
}
```

```{r, include=FALSE}
library(ggplot2)
colores <- scales::brewer_pal(palette = "Set1")(length(unique(cluster)))
```



```{r, echo=FALSE, warning=FALSE, fig.cap = "Medias del Número de familiares del cliente por clúster respecto la media global", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, y = dades$CNT_FAM_MEMBERS)) +
  geom_bar(stat = "summary", fun = "mean", fill= colores) +
  coord_cartesian(ylim=c(2,2.5))+
  geom_hline(yintercept = mean(dades$CNT_FAM_MEMBERS)) +
  labs(title = "Medias del Número de familiares del cliente por clúster respecto la media global" , y = "Media", x = "Clúster")
```

```{r, echo=FALSE, warning=FALSE, fig.cap = "Medias del logaritmo de los Ingresos totales del cliente por clúster respecto la media global", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, y = dades$log_AMT_INCOME_TOTAL)) +
  geom_bar(stat = "summary", fun = "mean", fill= colores) +
  geom_hline(yintercept = mean(dades$log_AMT_INCOME_TOTAL)) +
  labs(title = "Medias del logaritmo de los Ingresos totales del cliente por clúster respecto la media global" , y = "Media", x = "Clúster") 
```

```{r, echo=FALSE, warning=FALSE, fig.cap = "Medias del Importe de crédito del préstamo por clúster respecto la media global" , fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, y = dades$log_AMT_CREDIT)) +
  geom_bar(stat = "summary", fun = "mean", fill= colores) +
  geom_hline(yintercept = mean(dades$log_AMT_CREDIT)) +
  labs(title = "Medias del Importe de crédito del préstamo por clúster respecto la media global" , y = "Media", x = "Clúster")
```

```{r, echo=FALSE, warning=FALSE, fig.cap =  "Medias de la Edad por clúster respecto la media global", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, y = dades$AGE_YEARS)) +
  geom_bar(stat = "summary", fun = "mean", fill= colores) +
  geom_hline(yintercept = mean(dades$AGE_YEARS)) +
  labs(title = "Medias de la Edad por clúster respecto la media global" , y = "Media", x = "Clúster")

```

```{r, echo=FALSE, warning=FALSE, fig.cap = "Gráfico de la distribución del Género respecto el Clúster", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, fill = dades$CODE_GENDER)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución del Género respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))
```

```{r, echo=FALSE, warning=FALSE, fig.cap =  "Gráfico de la distribución del Tipo de ingresos respecto el Clúster", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, fill = dades$NAME_INCOME_TYPE)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución del Tipo de ingresos respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))
```

```{r, echo=FALSE, warning=FALSE, fig.cap = "Gráfico de la distribución del Nivel de estudios del cliente respecto el Clúster", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, fill = dades$NAME_EDUCATION_TYPE)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución del Nivel de estudios del cliente respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))
```

```{r, echo=FALSE, warning=FALSE, fig.cap = "Gráfico de la distribución del Estado civil respecto el Clúster", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, fill = dades$NAME_FAMILY_STATUS)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución del Estado civil respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))
```

```{r, echo=FALSE, warning=FALSE, fig.cap = "Gráfico de la distribución de la Actividad laboral respecto el Clúster", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, fill = dades$OCCUPATION_TYPE)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución de la Actividad laboral respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))
```

```{r, echo=FALSE, warning=FALSE, fig.cap = "Gráfico de la distribución del Tipo de organización donde trabaja el cliente respecto el Clúster", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, fill = dades$ORGANIZATION_TYPE)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución del Tipo de organización donde trabaja el cliente respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))
```

```{r, echo=FALSE, warning=FALSE, fig.cap = "Gráfico de la distribución de la Calificación de la región donde vive el cliente respecto el Clúster", fig.show='hold',out.width="75%",out.height="75%"}
ggplot(data = dades, aes(x = cluster, fill = dades$REGION_RATING_CLIENT)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución de la Calificación de la región donde vive el cliente respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))
```



## Profiling CURE

```{r, include = F, warning = F, message = F}
load("datos_profiling_CURE.RData")
```

```{r, include = F, warning = F, message = F}
library(ggplot2)
colores <- scales::brewer_pal(palette = "Set1")(length(unique(cluster)))
```

**Variables numéricas**

```{r, echo = F, warning = F, fig.height = 6, fig.width = 10}
ggplot(data = dades, aes(x = as.factor(unlist(cluster)), y = dades$OWN_CAR_AGE)) + 
  geom_bar(stat = "summary", fun = "mean", fill= colores) +
  coord_cartesian(ylim=c(8,12))+
  geom_hline(yintercept = mean(dades$OWN_CAR_AGE)) +
  labs(title = "Medias de la Edad en años del coche del cliente por clúster respecto la media global" , y = "Media", x = "Clúster") 
```


```{r, echo = F, warning = F, fig.height = 6, fig.width = 10}
ggplot(data = dades, aes(x = cluster, y = dades$CNT_FAM_MEMBERS)) +
  geom_bar(stat = "summary", fun = "mean", fill= colores) +
  geom_hline(yintercept = mean(dades$CNT_FAM_MEMBERS)) +
  labs(title = "Medias del Número de familiares del cliente por clúster respecto la media global" , y = "Media", x = "Clúster")
```


```{r, echo = F, warning = F, fig.height = 6, fig.width = 10}
ggplot(data = dades, aes(x = cluster, y = dades$log_AMT_INCOME_TOTAL)) +
  geom_bar(stat = "summary", fun = "mean", fill= colores) +
  coord_cartesian(ylim=c(11,12.5))+
  geom_hline(yintercept = mean(dades$log_AMT_INCOME_TOTAL)) +
  labs(title = "Medias del logaritmo de los Ingresos totales del cliente por clúster respecto la media global" , y = "Media", x = "Clúster") 
```


```{r, echo = F, warning = F, fig.height = 6, fig.width = 10}
ggplot(data = dades, aes(x = cluster, y = dades$log_AMT_CREDIT)) +
  geom_bar(stat = "summary", fun = "mean", fill= colores) +
  coord_cartesian(ylim=c(12.5,13.5))+
  geom_hline(yintercept = mean(dades$log_AMT_CREDIT)) +
  labs(title = "Medias del Importe de crédito del préstamo por clúster respecto la media global" , y = "Media", x = "Clúster")

```

```{r, echo = F, warning = F, fig.height = 6, fig.width = 10}
ggplot(data = dades, aes(x = cluster, y = dades$AGE_YEARS)) +
  geom_bar(stat = "summary", fun = "mean", fill= colores) +
  coord_cartesian(ylim=c(20,60))+
  geom_hline(yintercept = mean(dades$AGE_YEARS)) +
  labs(title = "Medias de la Edad por clúster respecto la media global" , y = "Media", x = "Clúster")

```

```{r, echo = F, warning = F, fig.height = 6, fig.width = 10}
ggplot(data = dades, aes(x = cluster, y = dades$RATIO_CREDIT_INCOME)) +
  geom_bar(stat = "summary", fun = "mean", fill= colores) +
  coord_cartesian(ylim=c(2,5))+
  geom_hline(yintercept = mean(dades$RATIO_CREDIT_INCOME)) +
  labs(title = "Medias del Ratio del Importe del préstamo por clúster respecto la media global" , y = "Media", x = "Clúster")
```


```{r, echo = F, warning = F}
ggplot(data = dades, aes(x = cluster, y = dades$RATIO_ANNUITY_CREDIT)) +
  geom_bar(stat = "summary", fun = "mean", fill= colores) +
  coord_cartesian(ylim=c(0.04,0.06))+
  geom_hline(yintercept = mean(dades$RATIO_ANNUITY_CREDIT)) +
  labs(title = "Medias del Ratio de la Anualidad del préstamo por clúster respecto la media global" , y = "Media", x = "Clúster")

```


```{r, echo = F, warning = F, fig.height = 6, fig.width = 10}
ggplot(data = dades, aes(x = cluster, y = dades$DTI_RATIO)) +
  geom_bar(stat = "summary", fun = "mean", fill= colores) +
  coord_cartesian(ylim=c(0.1,0.25))+
  geom_hline(yintercept = mean(dades$DTI_RATIO)) +
  labs(title = "Medias de la Capacidad de cliente para pagar la annuity con sus ingresos por clúster respecto la media global" , y = "Media", x = "Clúster")

```


**Variables categóricas**

```{r, echo = F, warning = F, message = F, fig.height = 6, fig.width = 10}
# tableData = table(cluster, dades$CODE_GENDER)
# length(tableData[1,])
# 
# for (i in 1:length(tableData[1,])) {
#   tableData[,i] = tableData[,i]/sum(tableData[,i])
# }
# 
# library(RColorBrewer)
# colors <- brewer.pal( length(tableData[1,]) , "Greens")
# barplot(tableData,
#         legend.text = TRUE,
#         args.legend = list(x="topleft"),
#         beside = TRUE, col = colors, ylim =  c(0,0.6))
ggplot(data = dades, aes(x = cluster, fill = dades$CODE_GENDER)) +
  geom_bar(position = "fill") +
  labs(title = "Gráfico de la distribución del Género respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))
```


```{r, echo = F, warning = F, message = F, fig.height = 6, fig.width = 10}
ggplot(data = dades, aes(x = cluster, fill = dades$NAME_INCOME_TYPE)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución del Tipo de ingresos respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))

# tableData = table(cluster, dades$NAME_INCOME_TYPE)
# 
# for (i in 1:length(tableData[1,])) {
#   tableData[,i] = tableData[,i]/sum(tableData[,i])
# }
# 
# colors <- colorRamps::blue2green(length(tableData[,1]))
# barplot(tableData,
#         legend.text = TRUE,
#         args.legend = list(x="topleft"),
#         beside = TRUE, col = colors, ylim =  c(0,1))

```


```{r, echo = F, warning = F, message = F, fig.height = 6, fig.width = 10}
ggplot(data = dades, aes(x = cluster, fill = dades$NAME_EDUCATION_TYPE)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución del Nivel de estudios del cliente respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))

# tableData = table(cluster,dades$NAME_EDUCATION_TYPE)
# for (i in 1:length(tableData[1,])) {
#   tableData[,i] = tableData[,i]/sum(tableData[,i])
# }
# 
# colors <- colorRamps::blue2green(length(tableData[,1]))
# barplot(tableData,
#         legend.text = TRUE,
#         args.legend = list(x="topleft"),
#         beside = TRUE, col = colors, ylim =  c(0,1))

```

```{r, echo = F, warning = F, message = F, fig.height = 6, fig.width = 10}
ggplot(data = dades, aes(x = cluster, fill = dades$NAME_FAMILY_STATUS)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución del Estado civil respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))

# tableData = table( cluster,dades$NAME_FAMILY_STATUS)
# for (i in 1:length(tableData[1,])) {
#   tableData[,i] = tableData[,i]/sum(tableData[,i])
# }
# colors <- colorRamps::blue2green(length(tableData[,1]))
# barplot(tableData,
#         legend.text = TRUE,
#         beside = TRUE, col = colors, ylim =  c(0,1))

```

```{r, echo = F, warning = F, message = F, fig.height = 6, fig.width = 10}
ggplot(data = dades, aes(x = cluster, fill = dades$OCCUPATION_TYPE)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución de la Actividad laboral respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))

# tableData = table( cluster,dades$OCCUPATION_TYPE)
# for (i in 1:length(tableData[1,])) {
#   tableData[,i] = tableData[,i]/sum(tableData[,i])
# }
# colors <- colorRamps::blue2green(length(tableData[,1]))
# barplot(tableData,
#         legend.text = TRUE,
#         args.legend = list(x="topleft"),
#         beside = TRUE, col = colors, ylim =  c(0,1))
# 
# tableData

```


```{r, echo = F, warning = F, message = F, fig.height = 6, fig.width = 10}
ggplot(data = dades, aes(x = cluster, fill = dades$ORGANIZATION_TYPE)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución del Tipo de organización donde trabaja el cliente respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))

# tableData = table(cluster,dades$ORGANIZATION_TYPE)
# for (i in 1:length(tableData[1,])) {
#   tableData[,i] = tableData[,i]/sum(tableData[,i])
# }
# 
# colors <- colorRamps::blue2green(length(tableData[,1]))
# barplot(tableData,
#         legend.text = TRUE,
#         args.legend = list(x="topleft"),
#         beside = TRUE, ylim =  c(0,1), col = colors)


```


```{r, echo = F, warning = F, message = F, fig.height = 6, fig.width = 10}
ggplot(data = dades, aes(x = cluster, fill = dades$REGION_RATING_CLIENT)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución de la Calificación de la región donde vive el cliente respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))

# tableData = table( cluster,dades$REGION_RATING_CLIENT)
# for (i in 1:length(tableData[1,])) {
#   tableData[,i] = tableData[,i]/sum(tableData[,i])
# }
# colors <- colorRamps::blue2green(length(tableData[,1]))
# barplot(tableData,
#         legend.text = TRUE,
#         args.legend = list(x="topleft"),
#         beside = TRUE, col = colors, ylim =  c(0,1))

```

```{r, echo = F, warning = F}
ggplot(data = dades, aes(x = cluster, fill = dades$NAME_INCOME_TYPE)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución del Tipo de ingresos respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))

# tableData = table(unlist(clusterIndividuo), df_preprocessed$TARGET)
# 
# for (i in 1:length(tableData[1,])) {
#   tableData[,i] = tableData[,i]/sum(tableData[,i])
# }
# 
# colors <- colorRamps::blue2red(length(tableData[,1]))
# barplot(tableData,
#         legend.text = TRUE,
#         args.legend = list(x="topleft"),
#         beside = TRUE, col = colors, ylim =  c(0,1))
```


```{r, echo = F, warning = F}
ggplot(data = dades, aes(x = cluster, fill = dades$TARGET)) +
  geom_bar(position = "dodge") +
  labs(title = "Gráfico de la distribución del Tipo de ingresos respecto el Clúster", y = "Freq", x = "Clúster") +
  theme(legend.position = "top") + guides(fill = guide_legend(title = NULL))
```
