---
title: "profiling"
author: "oskar"
date: "2023-10-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Cargamos los datos
```{r}
load("data_clust.Rdata")
```

```{r}
cluster6 <- mydata$cluster
cluster3 <- mydata$cluster2
mydata$cluster2 <- mydata$cluster <- NULL
dades <- mydata
```

CATEGORICAS
```{r}
cluster <- cluster6
indices_categoricas <- sapply(dades, is.factor)
p_values <- numeric(length(dades))

# Realiza pruebas de chi-cuadrado para las variables categóricas
for (i in which(indices_categoricas)) {
  variable_categorica <- dades[, i]
  cross_table <- table(variable_categorica, cluster)
  chi_square_result <- chisq.test(cross_table)
  p_values[i] <- chi_square_result$p.value
}


# Muestra los resultados
p_values_categoricas <- data.frame(
  Variable = names(dades)[indices_categoricas],
  P_Value = p_values[indices_categoricas]
)
print(p_values_categoricas)

```
NUMERICAS
```{r}
library(car)
# Identifica las variables categóricas (factores)
variables_categoricas <- sapply(dades, is.factor)

# Filtra las variables numéricas
variables_numericas <- dades[!variables_categoricas]
# Inicializa un objeto para almacenar los p valores de la ANOVA
p_values_numericas <- list()

# Realiza un ANOVA para cada variable numérica en función de cluster6 y cluster3
for (i in 1:ncol(variables_numericas)) {
  variable_name <- names(variables_numericas)[i]
  
  formula_cluster <- as.formula(paste(variable_name, " ~ cluster"))
  anova_result_cluster <- Anova(lm(formula_cluster, data = variables_numericas))
  
  # Almacena los p-valores de la ANOVA en p_values_anova
  p_values_numericas[[variable_name]] <- c(Cluster = anova_result_cluster[["Pr(>F)"]][1])
}

# Muestra el objeto con los p-valores de la ANOVA
print(p_values_numericas)
```
SIGNIFICATIVAS
```{r}
# Función para evaluar significancia de p-valores
evaluate_p_values <- function(p_values, alpha = 0.05) {
  significance <- ifelse(p_values <= alpha, 1, 0)
  return(significance)
}

# Evalúa significancia de p-valores para variables numéricas y categóricas
significance_numericas <- evaluate_p_values(p_values_numericas)
significance_categoricas <- evaluate_p_values(p_values_categoricas)

print("Significancia de p-valores para variables numéricas:")
print(significance_numericas)

print("Significancia de p-valores para variables categóricas:")
print(significance_categoricas)
```

```{r}
# install.packages("FactoMineR")
library(FactoMineR)
dadesc <- cbind(dades,factor(cluster))
resul <- catdes(dadesc,num.var=21,proba=0.05)
resul$test.chi2
resul$quanti
resul$category
```


GENERADOR DE GRAFS PARA VER CUAL NOS QUEDAMOS
```{r}
#número de variables
K <- ncol(dades)
#grupos de los clústers
P <- cluster
nameP <- "classe"
#número de clústers
nc <- length(levels(factor(P)))
#número de observaciones
n <- dim(dades)[1]


for(k in 1:K){
  if (is.numeric(dades[,k])){ # && significativa[k]==1
    print(paste("Anàlisi per classes de la Variable:", names(dades)[k]))
    barplot(tapply(dades[[k]], P, mean),main=paste("Means of", names(dades)[k], "by", nameP ))
    abline(h=mean(dades[[k]]))
    legend(0,mean(dades[[k]]),"global mean",bty="n")
    print("Estadístics per groups:")
    for(s in levels(as.factor(P))) {print(summary(dades[P==s,k]))}
    o<-oneway.test(dades[,k]~P)
    print(paste("p-valueANOVA:", o$p.value))
    kw<-kruskal.test(dades[,k]~P)
    print(paste("p-value Kruskal-Wallis:", kw$p.value))
    # print("p-values ValorsTest: ")
    # print(pvalk[,k])
  }else if(!is.numeric(dades[,k])){ #&& significativa[k]==1
      #qualitatives

      print(paste("Variable", names(dades)[k]))
      table<-table(P,dades[,k])
      #   print("Cross-table")
      #   print(table)
      rowperc<-prop.table(table,1)

      colperc<-prop.table(table,2)
      #  print("Distribucions condicionades a files")
      # print(rowperc)

      #ojo porque si la variable es true o false la identifica con el tipo Logical i

      dades[,k]<-as.factor(dades[,k])


      marg <- table(as.factor(P))/n
      print(append("Categories=",levels(as.factor(dades[,k]))))

      #from next plots, select one of them according to your practical case

      par(mar=c(5, 4, 4, 8), xpd=TRUE)
      plot(marg,type="l",ylim=c(0,1),main=paste("Prop. of pos & neg by",names(dades)[k]))
      paleta<-rainbow(length(levels(dades[,k])))
      for(c in 1:length(levels(dades[,k]))){lines(colperc[,c],col=paleta[c]) }
      legend("topright", levels(dades[,k]), col=paleta, lty=2, cex=0.6)

      #condicionades a classes
      print(append("Categories=",levels(dades[,k])))
      par(mar=c(5, 4, 4, 8), xpd=TRUE)
      plot(marg,type="n",ylim=c(0,1),main=paste("Prop. of pos & neg by",names(dades)[k]))
      paleta<-rainbow(length(levels(dades[,k])))
      for(c in 1:length(levels(dades[,k]))){lines(rowperc[,c],col=paleta[c]) }
      legend("topright", levels(dades[,k]), col=paleta, lty=2, cex=0.6)

      #amb variable en eix d'abcisses
      marg <-table(dades[,k])/n
      print(append("Categories=",levels(dades[,k])))
      par(mar=c(5, 4, 4, 8), xpd=TRUE)
      plot(marg,type="l",ylim=c(0,1),main=paste("Prop. of pos & neg by",names(dades)[k]), las=3)
      #x<-plot(marg,type="l",ylim=c(0,1),main=paste("Prop. of pos & neg by",names(dades)[k]), xaxt="n")
      #text(x=x+.25, y=-1, adj=1, levels(CountryName), xpd=TRUE, srt=25, cex=0.7)
      paleta<-rainbow(length(levels(as.factor(P))))
      for(c in 1:length(levels(as.factor(P)))){lines(rowperc[c,],col=paleta[c]) }
      legend("topright", levels(as.factor(P)), col=paleta, lty=2, cex=0.6)

      #condicionades a columna
      par(mar=c(5, 4, 4, 8), xpd=TRUE)
      plot(marg,type="n",ylim=c(0,1),main=paste("Prop. of pos & neg by",names(dades)[k]), las=3)
      paleta<-rainbow(length(levels(as.factor(P))))
      for(c in 1:length(levels(as.factor(P)))){lines(colperc[c,],col=paleta[c]) }
      legend("topright", levels(as.factor(P)), col=paleta, lty=2, cex=0.6)

      table<-table(dades[,k],P)
      print("Cross Table:")
      print(table)
      print("Distribucions condicionades a columnes:")
      print(colperc)

      #diagrames de barres adosades
      par(mar=c(5, 4, 4, 8), xpd=TRUE)
      barplot(table(dades[,k], as.factor(P)), beside=TRUE,col=paleta)
      legend("topright",levels(as.factor(dades[,k])),pch=1,cex=0.5, col=paleta)

      print("Test Chi quadrat: ")
      print(chisq.test(dades[,k], as.factor(P)))

     

      # g[k] <- ValorTestXquali(P,dades[,k])
      #calcular els pvalues de les quali
    }
  }#endfor
```
```{r}
library(ggplot2)
ggplot(dades, aes(x = P, y = dades$log_AMT_ANNUITY)) +
  geom_bar(stat = "summary", fun = "mean", fill = "blue") +
  labs(title = paste("Means of", names(dades)[3], "by", nameP),
       x = names(dades)[1],
       y = "Mean Value") +
  geom_hline(yintercept = mean(dades$log_AMT_ANNUITY), color = "red", linetype = "dashed") +
  theme_minimal()
```

```{r}

```








DONDE PONGA num_var o cat_var es donde se pone la variable que quieres graficar
```{r}
# VARIABLE NUM AGRUPANDO POR CLUSTER P
library(ggplot2)

# GRAF DE LA PROPORCION POSITIVA YNEGATIvA DE VALORESP POR CATEGORIA
ggplot(data = dades, aes(x = P, y = dades$log_AMT_ANNUITY)) +
  geom_line(stat = "summary", fun.y = "mean") +
  geom_hline(yintercept = mean(dades$log_AMT_ANNUITY)) +
  labs(title = paste("Means of", names(dades)[k], "by", nameP), y = "Mean")

#bARPLOT
ggplot(data = dades, aes(x = P, y = dades$log_AMT_ANNUITY)) +
  geom_bar(stat = "summary", fun = "mean") +
  geom_hline(yintercept = mean(dades$log_AMT_ANNUITY)) +
  labs(title = paste("Means of", names(dades)[k], "by", nameP), y = "Mean")

```
este da error idk
```{r}
# CATEGORICA AGRUPANDO POR P
library(ggplot2)

# pORPORCION POSITIVA Y NEGATIVA DE VALORES POR CATEGORIA, CONDICIONADO EN LAS FILAS
ggplot(data = dades, aes(x = P, y = prop.table(table(P, dades$CODE_GENDER))[,"positive"])) +
  geom_line() +
  labs(title = paste("Prop. of pos & neg by", names(dades)[k]), y = "Proportion") +
  theme(legend.position = "top")


# CATEGORICA AGRUPANDO POR P
library(ggplot2)

# pORPORCION POSITIVA Y NEGATIVA DE VALORES POR CATEGORIA, CONDICIONADO EN LAS COLUMNAS
ggplot(data = dades, aes(x = P, y = prop.table(table(dades$CODE_GENDER, P))["positive",])) +
  geom_line() +
  labs(title = paste("Prop. of pos & neg by", names(dades)[k]), y = "Proportion") +
  theme(legend.position = "top")

```

```{r}
# CATEGORICA AGRUPANDO POR P
library(ggplot2)

# GRAFICO DE LA PROPORCION DE VALORES POR CATEGORIA CON LA VARIABLE NE EL EJE X
ggplot(data = dades, aes(x = dades$CODE_GENDER)) +
  geom_bar(aes(fill = P), position = "fill") +
  labs(title = paste("Prop. of pos & neg by", names(dades)[k]), y = "Proportion", x = "Categories") +
  theme(legend.position = "top")

#Barplot
ggplot(data = dades, aes(x = P, fill = dades$CODE_GENDER)) +
  geom_bar(position = "dodge") +
  labs(title = paste("Prop. of pos & neg by", names(dades)[k]), y = "Proportion") +
  theme(legend.position = "top")

```


